# Fitur Bluetooth
CONFIG_ZMK_BLE=y
CONFIG_ZMK_SLEEP=y

# Nama Bluetooth Keyboard
CONFIG_ZMK_KEYBOARD_NAME="T9 SuperMini"

# Fitur Mouse (untuk Left Click)
CONFIG_ZMK_MOUSE=y

# Power Management (Deep Sleep 15 menit)
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000